import { Platform } from 'react-native';

export const Colors = {
  light: {
    text: '#1a1a1a',
    textSecondary: '#6b7280',
    textTertiary: '#9ca3af',
    background: '#fafafa',
    surface: '#ffffff',
    surfaceElevated: '#ffffff',
    tint: '#2563eb',
    tintLight: '#dbeafe',
    icon: '#6b7280',
    iconSecondary: '#9ca3af',
    tabIconDefault: '#9ca3af',
    tabIconSelected: '#2563eb',
    border: '#e5e7eb',
    borderLight: '#f3f4f6',
    success: '#10b981',
    successLight: '#d1fae5',
    warning: '#f59e0b',
    warningLight: '#fef3c7',
    error: '#ef4444',
    errorLight: '#fee2e2',
    overlay: 'rgba(0, 0, 0, 0.5)',
    shadow: 'rgba(0, 0, 0, 0.08)',
  },
  dark: {
    text: '#f9fafb',
    textSecondary: '#9ca3af',
    textTertiary: '#6b7280',
    background: '#0f0f0f',
    surface: '#1a1a1a',
    surfaceElevated: '#262626',
    tint: '#3b82f6',
    tintLight: '#1e3a5f',
    icon: '#9ca3af',
    iconSecondary: '#6b7280',
    tabIconDefault: '#6b7280',
    tabIconSelected: '#3b82f6',
    border: '#374151',
    borderLight: '#1f2937',
    success: '#34d399',
    successLight: '#064e3b',
    warning: '#fbbf24',
    warningLight: '#78350f',
    error: '#f87171',
    errorLight: '#7f1d1d',
    overlay: 'rgba(0, 0, 0, 0.7)',
    shadow: 'rgba(0, 0, 0, 0.3)',
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: 'system-ui',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});