import { TranslationKeys } from "./translations";

export const en: TranslationKeys = {
  common: {
    accept: "Accept",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    error: "There was an unexpected error",
    update: "Update",
    error_save: "There was an error while saving",
  },
  tabs: {
    projects: "Projects",
    home: "Home",
    calendar: "Calendar",
    data: "Dashboard",
  },
  projects: {
    add_project: "New project",
    empty_list: "There's no projects yet",
    new_project: "New project",
    label_name: "Project's name",
    placeholder_name: "Ex: Working, Studying",
    label_color: "Color identifier",
    label_icon: "Project's icon",
    name_required: "Project's name is required",
    name_min_length: "The project name must have at least 3 characters",
    delete_title: "Be careful!",
    delete_confirm: "Are you sure you want to delete project",
    delete_warning: "All the tasks and events associated will be deleted.",
    edit_project: "Edit project",
  },
  create: {
    select_project: "Select project",
    search_project: "Search project...",
    event: "Event",
    task: "Task",
    finance: "Finance",
    note: "Note",
    form_event: "Event Form",
    form_task: "Task Form",
    form_finance: "Finance Form",
    form_note: "Note Form",
  },
  notes: {
    title_label: "Title",
    title_placeholder: "Note title...",
    content_label: "Content",
    content_placeholder: "Write your note in markdown...",
    title_required: "Note title is required",
    title_too_long: "Title is too long (max 100 characters)",
    edit_mode: "Edit",
    preview_mode: "View",
  },
};
