import { TranslationKeys } from "./translations";

export const es: TranslationKeys = {
  common: {
    accept: "Aceptar",
    cancel: "Cancelar",
    save: "Guardar",
    delete: "Eliminar",
    error: "Hubo un error inesperado",
    update: "Actualizar",
    error_save: "Hubo un error al guardar",
    search: "Buscar",
    previous: "Anterior",
    next: "Siguiente",
    items: "elementos",
    select_date: "Seleccionar fecha",
    clear: "Limpiar",
    year: "Año",
    month: "Mes",
    day: "Día",
    hour: "Hora",
    minute: "Minuto",
    minutes: "Minutos",
    hours: "Horas",
    days: "Días",
    weeks: "Semanas",
    months: "Meses",
    years: "Años",
    calendar: "Calendario",
    time: "Hora",
    select_unit: "Seleccionar unidad",
    yes: "Sí",
    no: "No",
  },
  tabs: {
    projects: "Proyectos",
    home: "Inicio",
    calendar: "Calendario",
    data: "Panel",
  },
  projects: {
    add_project: "Nuevo proyecto",
    empty_list: "No hay proyectos aun",
    new_project: "Nuevo Proyecto",
    label_name: "Nombre del Proyecto",
    placeholder_name: "Ej: Trabajo, Estudio...",
    label_color: "Color del proyecto",
    label_icon: "Icono del proyecto",
    name_required: "El nombre del proyecto es necesario",
    name_min_length: "El nombre del proyecto debe tener al menos 3 caracteres",
    delete_title: "Zona Peligrosa",
    delete_confirm: "¿Quieres borrar el proyecto",
    delete_warning: "Se perderán todas las tareas asociadas.",
    edit_project: "Editar proyecto",
  },
  create: {
    select_project: "Seleccionar proyecto",
    search_project: "Buscar proyecto...",
    event: "Evento",
    task: "Tarea",
    habit: "Hábito",
    finance: "Finanza",
    note: "Nota",
    form_event: "Formulario de Evento",
    form_task: "Formulario de Tarea",
    form_habit: "Formulario de Hábito",
    form_finance: "Formulario de Finanzas",
    form_note: "Formulario de Nota",
  },
  notes: {
    title_label: "Título",
    title_placeholder: "Título de la nota...",
    content_label: "Contenido",
    content_placeholder: "Escribe tu nota aquí...",
    title_required: "El título de la nota es requerido",
    title_too_long: "El título es demasiado largo",
    edit_mode: "Editar",
    preview_mode: "Vista previa",
    search_placeholder: "Buscar notas...",
    empty_list: "No hay notas todavía",
    no_results: "No se encontraron notas",
  },
  finance: {
    title_label: "Título",
    title_placeholder: "Título de la finanza...",
    title_required: "El título es requerido",
    amount_label: "Cantidad",
    amount_placeholder: "0.00",
    amount_required: "La cantidad es requerida",
    amount_hint: "Los valores negativos son para gastos",
    currency_label: "Moneda",
    currency_required: "La moneda es requerida",
    delete_title: "Zona de peligro",
    delete_confirm: "¿Quieres borrar esta finanza?",
    add_execution: "Agregar ejecución",
    for_finance: "Para",
    total_label: "Total",
    executions_label: "Ejecuciones",
    independent_label: "Finanzas independientes",
    edit: "Editar",
    add_execution_btn: "Agregar ejecución",
    no_executions: "No hay ejecuciones todavía",
    no_finances: "No hay finanzas todavía",
  },
  task: {
    section_title: "Tareas",
    title_label: "Título",
    title_placeholder: "Título de la tarea...",
    title_required: "El título de la tarea es requerido",
    due_date_label: "Fecha de vencimiento",
    due_date_placeholder: "Seleccionar fecha de vencimiento",
    location_label: "Ubicación",
    location_placeholder: "Ubicación de la tarea...",
    completion_by_label: "Completado por",
    executions_count: "Cantidad",
    execution_time: "Tiempo",
    count_goal_label: "Meta de cantidad",
    count_goal_placeholder: "Número de veces",
    count_goal_required: "La cantidad debe ser mayor a cero",
    time_goal_label: "Meta de tiempo",
    time_goal_required: "El tiempo debe ser mayor a cero",
    time_value_placeholder: "Cantidad",
    habit_due_time_helper: "Tiempo para calcular la fecha de vencimiento de las tareas creadas por este hábito",
    select_unit: "Seleccionar unidad",
    executions_label: "Ejecuciones",
    no_executions: "No hay ejecuciones todavía",
    progress_label: "Progreso",
    progress_count: "{count} de {goal} ejecuciones",
    progress_time: "{minutes} de {goal} minutos",
    complete: "Completado",
    incomplete: "Incompleto",
    start_execution: "Iniciar",
    stop_execution: "Detener",
    delete_execution: "Eliminar ejecución",
    delete_confirm: "¿Estás seguro de eliminar esta ejecución?",
    edit_task: "Editar tarea",
    delete_task: "Eliminar tarea",
    task_detail: "Detalle de tarea",
  },
  habit: {
    title_label: "Título",
    title_placeholder: "Título del hábito...",
    title_required: "El título del hábito es requerido",
    is_strict_label: "Es estricto",
    is_strict_helper: "Cuando es estricto, las tareas generadas se eliminan después del tiempo de vencimiento",
    due_time_label: "Tiempo de vencimiento",
    begin_at_label: "Fecha de inicio",
    begin_at_placeholder: "Seleccionar fecha de inicio",
    location_label: "Ubicación",
    location_placeholder: "Ubicación del hábito...",
    completion_by_label: "Completado por",
    executions_count: "Cantidad",
    execution_time: "Tiempo",
    count_goal_label: "Meta de cantidad",
    count_goal_placeholder: "Número de veces",
    count_goal_required: "La cantidad debe ser mayor a cero",
    time_goal_required: "El tiempo debe ser mayor a cero",
    recurrence_label: "Recurrencia",
    recurrence_required: "La recurrencia es requerida",
    every: "Cada",
    until: "hasta",
    frequency: "Frecuencia",
    interval: "Intervalo",
    on_days: "En días",
    on_day_of_month: "En el día del mes",
    ends: "Termina",
    end_never: "Nunca",
    end_count: "Después de",
    end_until: "En fecha",
    times: "veces",
    select_end_date: "Seleccionar fecha de fin",
    daily: "Diario",
    weekly: "Semanal",
    monthly: "Mensual",
    yearly: "Anual",
    recurrence: "Recurrencia",
    today: "Hoy",
    tomorrow: "Mañana",
    days: "días",
  },
  habits: {
    section_title: "Hábitos",
    no_habits: "No hay hábitos todavía",
    edit_habit: "Editar hábito",
    delete_habit: "Eliminar hábito",
    delete_confirm: "¿Estás seguro de eliminar este hábito?",
  },
};
