import { TranslationKeys } from "./translations";

export const es: TranslationKeys = {
  common: {
    accept: "Aceptar",
    cancel: "Cancelar",
    save: "Guardar",
    delete: "Eliminar",
    error: "Hubo un error inesperado",
    update: "Actualizar",
    error_save: "Hubo un error al guardar",
  },
  tabs: {
    projects: "Proyectos",
    home: "Inicio",
    calendar: "Calendario",
    data: "Panel",
  },
  projects: {
    add_project: "Nuevo proyecto",
    empty_list: "No hay proyectos aun",
    new_project: "Nuevo Proyecto",
    label_name: "Nombre del Proyecto",
    placeholder_name: "Ej: Trabajo, Estudio...",
    label_color: "Color del proyecto",
    label_icon: "Icono del proyecto",
    name_required: "El nombre del proyecto es necesario",
    name_min_length: "El nombre del proyecto debe tener al menos 3 caracteres",
    delete_title: "Zona Peligrosa",
    delete_confirm: "¿Quieres borrar el proyecto",
    delete_warning: "Se perderán todas las tareas asociadas.",
    edit_project: "Editar proyecto",
  },
  create: {
    select_project: "Seleccionar proyecto",
    search_project: "Buscar proyecto...",
    event: "Evento",
    task: "Tarea",
    finance: "Finanza",
    note: "Nota",
    form_event: "Formulario de Evento",
    form_task: "Formulario de Tarea",
    form_finance: "Formulario de Finanzas",
    form_note: "Formulario de Nota",
  },
  notes: {
    title_label: "Título",
    title_placeholder: "Título de la nota...",
    content_label: "Contenido",
    content_placeholder: "Escribe tu nota en markdown...",
    title_required: "El título de la nota es obligatorio",
    title_too_long: "El título es demasiado largo (máximo 100 caracteres)",
    edit_mode: "Editar",
    preview_mode: "Vista",
  },
};
