import { TranslationKeys } from "./translations";

export const es: TranslationKeys = {
  common: {
    accept: "Aceptar",
    cancel: "Cancelar",
    save: "Guardar",
    delete: "Eliminar",
    error: "Hubo un error inesperado",
    update: "Actualizar",
    error_save: "Hubo un error al guardar",
    search: "Buscar",
    previous: "Anterior",
    next: "Siguiente",
    items: "elementos",
    select_date: "Seleccionar fecha",
    clear: "Limpiar",
    year: "Año",
    month: "Mes",
    day: "Día",
    hour: "Hora",
    minute: "Minuto",
    minutes: "Minutos",
    hours: "Horas",
    days: "Días",
    weeks: "Semanas",
    months: "Meses",
    years: "Años",
    calendar: "Calendario",
    time: "Hora",
    select_unit: "Seleccionar unidad",
  },
  tabs: {
    projects: "Proyectos",
    home: "Inicio",
    calendar: "Calendario",
    data: "Panel",
  },
  projects: {
    add_project: "Nuevo proyecto",
    empty_list: "No hay proyectos aun",
    new_project: "Nuevo Proyecto",
    label_name: "Nombre del Proyecto",
    placeholder_name: "Ej: Trabajo, Estudio...",
    label_color: "Color del proyecto",
    label_icon: "Icono del proyecto",
    name_required: "El nombre del proyecto es necesario",
    name_min_length: "El nombre del proyecto debe tener al menos 3 caracteres",
    delete_title: "Zona Peligrosa",
    delete_confirm: "¿Quieres borrar el proyecto",
    delete_warning: "Se perderán todas las tareas asociadas.",
    edit_project: "Editar proyecto",
  },
  create: {
    select_project: "Seleccionar proyecto",
    search_project: "Buscar proyecto...",
    event: "Evento",
    task: "Tarea",
    habit: "Hábito",
    finance: "Finanza",
    note: "Nota",
    form_event: "Formulario de Evento",
    form_task: "Formulario de Tarea",
    form_habit: "Formulario de Hábito",
    form_finance: "Formulario de Finanzas",
    form_note: "Formulario de Nota",
  },
  notes: {
    title_label: "Título",
    title_placeholder: "Título de la nota...",
    content_label: "Contenido",
    content_placeholder: "Escribe tu nota en markdown...",
    title_required: "El título de la nota es obligatorio",
    title_too_long: "El título es demasiado largo (máximo 100 caracteres)",
    edit_mode: "Editar",
    preview_mode: "Vista",
    search_placeholder: "Buscar en notas...",
    empty_list: "No hay notas en este proyecto",
    no_results: "No se encontraron notas",
  },
  finance: {
    title_label: "Título",
    title_placeholder: "Ej: Salario, Alquiler...",
    title_required: "El título es requerido",
    amount_label: "Monto",
    amount_placeholder: "0.00",
    amount_required: "El monto debe ser mayor a cero",
    amount_hint: "Los valores negativos son para gastos",
    currency_label: "Moneda",
    currency_required: "La moneda es requerida",
    delete_title: "Eliminar Finance",
    delete_confirm: "¿Estás seguro de eliminar esta transacción?",
    add_execution: "Agregar Ejecución",
    for_finance: "Para",
    total_label: "Balance Total",
    executions_label: "Ejecuciones",
    independent_label: "Finanzas",
    edit: "Editar",
    add_execution_btn: "Agregar",
    no_executions: "No hay ejecuciones aún",
    no_finances: "No hay finanzas en este proyecto",
  },
  task: {
    title_label: "Título",
    title_placeholder: "Título de la tarea...",
    title_required: "El título es requerido",
    due_date_label: "Fecha de vencimiento",
    due_date_placeholder: "Seleccionar fecha",
    location_label: "Ubicación",
    location_placeholder: "Nombre del lugar...",
    completion_by_label: "Tipo de completado",
    executions_count: "Cantidad",
    execution_time: "Tiempo",
    count_goal_label: "Meta de cantidad",
    count_goal_placeholder: "Número de veces",
    count_goal_required: "La cantidad debe ser mayor a cero",
    time_goal_label: "Meta de tiempo",
    time_goal_required: "El tiempo debe ser mayor a cero",
    time_value_placeholder: "Cantidad",
    habit_due_time_helper: "Tiempo para calcular la fecha de vencimiento de las tareas creadas por este habito",
    select_unit: "Seleccionar unidad",
  },
};
